### PR TITLE
featured artists lul

### PR DESCRIPTION
**Pull request by j0code**
- @feat meta tag
- guessing
- points (extra +0.5 points)
- refactored some code

#### Please test it before reviewing / merging

### CODE REVIEW

**Review by cfpwastaken — CHANGES_REQUESTED** [review]
Fix that thing where it doesnt say feat at start, then ill approve

**Comment by cfpwastaken** [comment]
when you make that quick fix you can merge. dont wait for me to approve

**Comment by j0code** [comment]
Imma just pretend @cfpwastaken approved

**Review by cfpwastaken — COMMENTED** [review]
approved

**Pull request merged**
