### PR TITLE
Despacito

### PR DESCRIPTION
**Pull request by cfpwastaken**
Not really good with timing tho. Will fix the timing when you add start feature so I can do this better.

### CODE REVIEW

**Review by j0code — COMMENTED** [review]
maybe try again with the lyrics out-of-sync patch and if it's synced, just merge it :)

**Review by j0code — COMMENTED** [review]
cringe

**Comment by cfpwastaken** [comment]
?

**Comment by j0code** [comment]
add to creelonestudios/lyrics instead

**Pull request closed without merging**
